name: CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" > ~/.kube/config

      - name: Update image tag
        run: |
          sed -i "s|ghcr.io/roei2212/shorty-service:latest|ghcr.io/${{ github.repository }}/shorty-service:${{ github.sha }}|g" k8s/staging/deployment.yaml

      - name: Apply manifests (no validation)
        run: kubectl apply --validate=false -f k8s/staging/

  deploy-production:
    name: Deploy to Production
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" > ~/.kube/config

      - name: Update image tag
        run: |
          sed -i "s|ghcr.io/roei2212/shorty-service:latest|ghcr.io/${{ github.repository }}/shorty-service:${{ github.sha }}|g" k8s/production/deployment.yaml

      - name: Apply manifests (no validation)
        run: kubectl apply --validate=false -f k8s/production/
